version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:15-alpine
    container_name: archive_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: archive_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: archive_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: